name: QA API Testing con Postman y Newman

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
    # 1. Descargar el repositorio con la colección JSON
    - name: Checkout código
      uses: actions/checkout@v4

    # 2. Instalar Node.js
    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    # 3. Instalar Newman y el reporter HTML extra
    - name: Instalar Newman y HTMLExtra
      run: |
        npm install -g newman
        npm install -g newman-reporter-htmlextra

    # 4. Ejecutar la colección exportada
    - name: Ejecutar Colección de Postman
      run: |
        newman run coleccion.json -r htmlextra --reporter-htmlextra-export reporte_api.html

    # 5. Subir el reporte visual generado en la nube
    - name: Publicar Reporte HTML
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: reporte-postman-api
        path: reporte_api.html