name: QA API Testing con Postman y Newman

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  api-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v4

    - name: Configurar Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22'

    - name: Instalar Newman y HTMLExtra
      run: |
        npm install -g newman
        npm install -g newman-reporter-htmlextra

    - name: Crear carpeta de reporte y ejecutar Newman
      run: |
        mkdir -p public
        newman run Pruebaspiplines.json -r cli,htmlextra --reporter-htmlextra-export public/index.html --suppress-exit-code

    - name: Configurar GitHub Pages
      uses: actions/configure-pages@v5

    - name: Subir artefacto de Pages
      uses: actions/upload-pages-artifact@v3
      with:
        path: 'public'

    - name: Desplegar en GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4